import { User } from './models/User.js'
import { Product } from './models/Product.js'
import { GiftBox } from './models/GiftBox.js'
import { Order } from './models/Order.js'

const img = {
  cinnamon: '/products/spices/cinnamon.png',
  pepper: '/products/spices/black-pepper.png',
  cardamom: '/products/spices/cardamom.png',
  cloves: '/products/spices/cloves.png',
  turmeric: '/products/spices/turmeric.png',
  cumin: '/products/spices/cumin.png',
  coriander: '/products/spices/coriander.png',
  nutmeg: '/products/spices/nutmeg.png',
  ginger: '/products/spices/ginger.png',
  fenugreek: '/products/spices/fenugreek.png',
  mustardSeeds: '/products/spices/mustard-seeds.png',
  redChili: '/products/spices/red-chili.png',
  bayLeaf: '/products/spices/bay-leaf.png',
  starAnise: '/products/spices/star-anise.png',
  saffron: '/products/spices/saffron.png',
  paprika: '/products/spices/paprika.png',
  fennelSeeds: '/products/spices/fennel-seeds.png',
  curryLeaves: '/products/spices/curry-leaves.png',
  tea: '/products/tea.jpg',
  curry: '/products/spices/curry-powder.png',
  curryLoose: '/products/curry.jpg',
  kokis: '/products/kokis.jpg',
  cashews: '/products/cashews.jpg',
  gift1: '/products/gift-taste.jpg',
  gift2: '/products/gift-tea.jpg',
  gift3: '/products/gift-birthday.jpg',
  gift4: '/products/gift-heritage.jpg',
  gift5: '/products/gift-corporate.jpg',
  spices: '/products/spices-banner.jpg',
  cinnamonLoose: '/products/cinnamon.jpg',
}

function p(data) {
  return {
    rating: 4.8,
    reviewCount: 24,
    active: true,
    dietary: ['See label'],
    occasions: ['Birthday', 'Thank You', 'Just Because'],
    interests: [],
    ...data,
    images: data.images || [data.image].filter(Boolean),
    qrPath: `/experience/${data.slug}`,
  }
}

export async function seedIfEmpty() {
  const count = await Product.countDocuments()
  if (count > 0) {
    console.log('[seed] Data already present — skip')
    return
  }

  console.log('[seed] Seeding SpiceBox Lanka demo data…')

  await User.create({
    name: 'SpiceBox Admin',
    email: 'admin@spiceboxlanka.lk',
    password: 'admin123',
    role: 'admin',
    phone: '+94112345678',
  })

  await User.create({
    name: 'Nimal Perera',
    email: 'customer@spiceboxlanka.lk',
    password: 'customer123',
    role: 'customer',
    phone: '0771234567',
    loyaltyPoints: 180,
    loyaltyLevel: 'Spice Explorer',
  })

  const products = await Product.insertMany([
    p({
      name: 'Ceylon Cinnamon',
      slug: 'ceylon-cinnamon',
      category: 'Spices',
      price: 850,
      stock: 120,
      image: img.cinnamon,
      shortDescription: 'True Ceylon cinnamon quills — delicate, sweet and fragrant.',
      description:
        'Hand-harvested Cinnamomum verum from southern Sri Lanka. Soft sweetness with citrus warmth — perfect for tea, baking and curries.',
      origin: 'Matara & Galle, Sri Lanka',
      ingredients: '100% Cinnamomum verum',
      usage: 'Add to tea, desserts, curries, or sprinkle over fruit.',
      storage: 'Cool, dry place away from sunlight.',
      tags: ['spice', 'cinnamon', 'gift-her', 'tourist'],
      interests: ['Spice Lover', 'Cooking Lover', 'Healthy Lifestyle', 'Sri Lankan Culture'],
      occasions: ['Birthday', 'Thank You', 'Tourist Gift', 'Housewarming'],
      culturalStory:
        'Ceylon cinnamon has been treasured for centuries as the true cinnamon of the island — once worth its weight along spice routes.',
      heritage:
        'Sri Lanka is world-famous for true cinnamon. Soft multi-layered quills distinguish it from cassia.',
      production:
        'Bark is carefully peeled from young stems, layered into quills, and sun-dried by skilled peelers.',
      recipe: {
        title: 'Ceylon Cinnamon Tea',
        ingredients: ['1 cup water', '1 Ceylon cinnamon stick', '1 tsp Ceylon tea', 'Honey optional'],
        steps: ['Boil water with cinnamon', 'Add tea and steep 3 minutes', 'Strain and sweeten lightly'],
        serving: 'Serve warm in the afternoon',
      },
      featured: true,
      bestSeller: true,
    }),
    p({
      name: 'Ceylon Black Pepper',
      slug: 'ceylon-black-pepper',
      category: 'Spices',
      price: 700,
      stock: 95,
      image: img.pepper,
      shortDescription: 'Bold aromatic black peppercorns from Sri Lankan estates.',
      description: 'Sun-dried Piper nigrum with floral heat — elevates everyday cooking.',
      origin: 'Matale, Sri Lanka',
      ingredients: '100% Piper nigrum',
      usage: 'Grind fresh over meats, soups and vegetable dishes.',
      storage: 'Airtight, dry cupboard.',
      tags: ['spice', 'pepper'],
      interests: ['Spice Lover', 'Cooking Lover'],
      culturalStory: 'Pepper once rivalled gold in value along maritime trade routes.',
      heritage: 'A cornerstone of Sri Lankan kitchens and Ayurvedic traditions.',
      production: 'Berries are harvested, fermented briefly and sun-dried to deep black.',
      recipe: {
        title: 'Sri Lankan Black Pepper Curry',
        ingredients: ['Protein', 'Cracked pepper', 'Garlic', 'Onion', 'Coconut milk'],
        steps: ['Toast pepper', 'Sauté aromatics', 'Simmer with coconut milk'],
        serving: 'With rice or roti',
      },
      bestSeller: true,
    }),
    p({
      name: 'Ceylon Cardamom',
      slug: 'ceylon-cardamom',
      category: 'Spices',
      price: 1100,
      stock: 70,
      image: img.cardamom,
      shortDescription: 'Green cardamom pods with floral sweetness.',
      description: 'Premium pods for tea blends, sweets and festive cooking.',
      origin: 'Kandy Highlands',
      ingredients: 'Whole green cardamom',
      usage: 'Crush lightly for tea, rice and desserts.',
      storage: 'Sealed to preserve oils.',
      tags: ['spice', 'cardamom', 'tea', 'gift-her'],
      interests: ['Tea Lover', 'Spice Lover', 'Premium Gifts'],
      occasions: ['Wedding', 'Anniversary', "Mother's Day"],
      culturalStory: 'Known as the queen of spices — central to Sri Lankan hospitality.',
      heritage: 'Offered in ceremonial sweets and fragrant milk teas.',
      production: 'Pods are hand-picked and dried to preserve green colour and aroma.',
      featured: true,
    }),
    p({
      name: 'Ceylon Cloves',
      slug: 'ceylon-cloves',
      category: 'Spices',
      price: 950,
      stock: 80,
      image: img.cloves,
      shortDescription: 'Intensely aromatic whole cloves.',
      description: 'Essential for biryani, pickles and festive spice mixes.',
      origin: 'Southern Province',
      ingredients: 'Whole dried clove buds',
      usage: 'Use sparingly in curries and baking.',
      storage: 'Cool, dry, airtight.',
      tags: ['spice', 'cloves'],
      interests: ['Spice Lover', 'Traditional Food Lover'],
      occasions: ['Christmas', 'New Year'],
      culturalStory: 'Cloves were among the island’s most prized export spices.',
      heritage: 'Used in traditional medicine and ceremonial cuisine.',
      production: 'Flower buds are harvested before opening and carefully dried.',
    }),
    p({
      name: 'Sri Lankan Curry Powder',
      slug: 'sri-lankan-curry-powder',
      category: 'Spices',
      price: 600,
      stock: 200,
      image: img.curry,
      shortDescription: 'Balanced house blend for authentic island curries.',
      description: 'Roasted coriander, cumin, fennel and chilli for everyday cooking.',
      origin: 'Colombo Blend Kitchen',
      ingredients: 'Coriander, cumin, fennel, chilli, turmeric, curry leaves',
      usage: 'Bloom in oil before adding vegetables or protein.',
      storage: 'Airtight jar away from heat.',
      tags: ['spice', 'curry'],
      interests: ['Cooking Lover', 'Traditional Food Lover', 'Spice Lover'],
      culturalStory: 'Every Sri Lankan household has its own cherished curry powder recipe.',
      heritage: 'The heartbeat of Sri Lankan home kitchens.',
      production: 'Spices are dry-roasted and ground in small batches.',
      bestSeller: true,
    }),
    p({
      name: 'Turmeric',
      slug: 'turmeric',
      category: 'Spices',
      price: 550,
      stock: 140,
      image: img.turmeric,
      shortDescription: 'Vibrant golden turmeric with earthy warmth.',
      description: 'Finely ground Sri Lankan turmeric for curries, rice and golden milk.',
      origin: 'Kurunegala, Sri Lanka',
      ingredients: '100% Curcuma longa',
      usage: 'Bloom in oil or stir into curries and drinks.',
      storage: 'Airtight away from light and moisture.',
      tags: ['spice', 'turmeric'],
      interests: ['Spice Lover', 'Cooking Lover', 'Healthy Lifestyle'],
      culturalStory: 'Turmeric is the golden heart of Sri Lankan home cooking.',
      heritage: 'Used in kitchens and ceremonial preparations across the island.',
      production: 'Rhizomes are cleaned, boiled, dried and milled.',
    }),
    p({
      name: 'Cumin',
      slug: 'cumin',
      category: 'Spices',
      price: 580,
      stock: 130,
      image: img.cumin,
      shortDescription: 'Toasty cumin with deep, savoury aroma.',
      description: 'Warm nutty cumin — a foundation spice for Sri Lankan curries and tempering.',
      origin: 'Dry Zone, Sri Lanka',
      ingredients: '100% Cuminum cyminum',
      usage: 'Dry-roast lightly, then grind or temper in hot oil.',
      storage: 'Cool, dry, airtight container.',
      tags: ['spice', 'cumin'],
      interests: ['Spice Lover', 'Cooking Lover', 'Traditional Food Lover'],
      culturalStory: 'Cumin brings the comforting base note of island spice blends.',
      heritage: 'Central to everyday Sri Lankan tempering and curry powders.',
      production: 'Seeds are cleaned and sun-dried for aroma.',
    }),
    p({
      name: 'Coriander',
      slug: 'coriander',
      category: 'Spices',
      price: 520,
      stock: 135,
      image: img.coriander,
      shortDescription: 'Citrusy coriander seeds for classic island blends.',
      description: 'Fragrant coriander seeds that form the backbone of Sri Lankan curry powder.',
      origin: 'Central Province, Sri Lanka',
      ingredients: '100% Coriandrum sativum seeds',
      usage: 'Roast and grind for curry powder, or temper whole.',
      storage: 'Airtight jar in a cool cupboard.',
      tags: ['spice', 'coriander'],
      interests: ['Spice Lover', 'Cooking Lover'],
      culturalStory: 'Coriander is the quiet hero of Sri Lankan spice craft.',
      heritage: 'Essential in household curry powders island-wide.',
      production: 'Seeds are harvested and dried to preserve citrus notes.',
    }),
    p({
      name: 'Nutmeg',
      slug: 'nutmeg',
      category: 'Spices',
      price: 980,
      stock: 75,
      image: img.nutmeg,
      shortDescription: 'Warm, sweet nutmeg for baking and festive cooking.',
      description: 'Whole nutmeg with rich sweetness — perfect for desserts and milk teas.',
      origin: 'Kandy District, Sri Lanka',
      ingredients: 'Whole Myristica fragrans',
      usage: 'Grate fresh over sweets, curries and beverages.',
      storage: 'Keep whole nuts sealed and dry.',
      tags: ['spice', 'nutmeg'],
      interests: ['Spice Lover', 'Cooking Lover', 'Premium Gifts'],
      occasions: ['Christmas', 'New Year', 'Thank You'],
      culturalStory: 'Nutmeg has long been treasured in Sri Lankan festive kitchens.',
      heritage: 'A classic note in sweetmeats and holiday cooking.',
      production: 'Nuts are dried carefully to protect oils.',
    }),
    p({
      name: 'Ginger',
      slug: 'ginger',
      category: 'Spices',
      price: 620,
      stock: 125,
      image: img.ginger,
      shortDescription: 'Zesty dried ginger with bright heat.',
      description: 'Sun-dried Sri Lankan ginger for tea, curries and baking.',
      origin: 'Southern Province, Sri Lanka',
      ingredients: '100% dried Zingiber officinale',
      usage: 'Steep in tea, grind for blends, or cook into curries.',
      storage: 'Cool, dry place in an airtight pouch.',
      tags: ['spice', 'ginger'],
      interests: ['Spice Lover', 'Healthy Lifestyle', 'Tea Lover'],
      culturalStory: 'Ginger is a daily comfort spice in Sri Lankan homes.',
      heritage: 'Used in cuisine and traditional wellness teas.',
      production: 'Rhizomes are sliced and sun-dried.',
    }),
    p({
      name: 'Fenugreek',
      slug: 'fenugreek',
      category: 'Spices',
      price: 540,
      stock: 110,
      image: img.fenugreek,
      shortDescription: 'Bittersweet fenugreek for authentic tempering.',
      description: 'Golden fenugreek seeds for sambols, pickles and curry bases.',
      origin: 'North Central Province, Sri Lanka',
      ingredients: '100% Trigonella foenum-graecum',
      usage: 'Temper sparingly in oil; do not burn.',
      storage: 'Airtight and dry.',
      tags: ['spice', 'fenugreek'],
      interests: ['Spice Lover', 'Traditional Food Lover', 'Cooking Lover'],
      culturalStory: 'A little fenugreek transforms island home cooking.',
      heritage: 'Signature in many traditional Sri Lankan recipes.',
      production: 'Seeds are cleaned and packed for freshness.',
    }),
    p({
      name: 'Mustard Seeds',
      slug: 'mustard-seeds',
      category: 'Spices',
      price: 500,
      stock: 145,
      image: img.mustardSeeds,
      shortDescription: 'Pungent mustard seeds for classic island tempering.',
      description: 'Mustard seeds that pop with heat in hot oil — essential for mallums and curries.',
      origin: 'Sri Lanka',
      ingredients: '100% Brassica juncea seeds',
      usage: 'Temper in oil until they pop, then add aromatics.',
      storage: 'Cool, dry, sealed pouch.',
      tags: ['spice', 'mustard'],
      interests: ['Spice Lover', 'Cooking Lover', 'Traditional Food Lover'],
      culturalStory: 'Mustard tempering is the fragrant start of countless dishes.',
      heritage: 'A cornerstone of everyday island cooking technique.',
      production: 'Seeds are cleaned and moisture-controlled.',
    }),
    p({
      name: 'Red Chili',
      slug: 'red-chili',
      category: 'Spices',
      price: 650,
      stock: 160,
      image: img.redChili,
      shortDescription: 'Sun-dried red chilli with bold island heat.',
      description: 'Vibrant dried red chillies for sambols, curries and chilli flakes.',
      origin: 'Puttalam & Anuradhapura, Sri Lanka',
      ingredients: '100% dried red chilli',
      usage: 'Grind for chilli powder or temper whole for aroma.',
      storage: 'Keep dry and sealed to preserve colour.',
      tags: ['spice', 'chili'],
      interests: ['Spice Lover', 'Cooking Lover', 'Traditional Food Lover'],
      culturalStory: 'Red chilli brings the lively heat that defines Sri Lankan flavour.',
      heritage: 'Central to pol sambol and countless home curries.',
      production: 'Chillies are sun-dried and sorted by colour.',
    }),
    p({
      name: 'Bay Leaf',
      slug: 'bay-leaf',
      category: 'Spices',
      price: 480,
      stock: 100,
      image: img.bayLeaf,
      shortDescription: 'Fragrant bay leaves for slow-cooked depth.',
      description: 'Dried bay leaves that add herbal warmth to rice, stews and spice mixes.',
      origin: 'Hill Country, Sri Lanka',
      ingredients: 'Dried bay leaves',
      usage: 'Add whole to rice, stocks and curries; remove before serving.',
      storage: 'Airtight container away from humidity.',
      tags: ['spice', 'bay-leaf'],
      interests: ['Spice Lover', 'Cooking Lover'],
      culturalStory: 'Bay leaf lends quiet complexity to celebratory cooking.',
      heritage: 'Used in festive rice and slow-simmered dishes.',
      production: 'Leaves are shade-dried to retain aroma.',
    }),
    p({
      name: 'Star Anise',
      slug: 'star-anise',
      category: 'Spices',
      price: 890,
      stock: 85,
      image: img.starAnise,
      shortDescription: 'Liquorice-sweet star anise for aromatic cooking.',
      description: 'Whole star anise for biryani, broths and spice infusions.',
      origin: 'Selected Sri Lankan spice partners',
      ingredients: 'Whole Illicium verum',
      usage: 'Simmer whole in rice, broths and festive dishes.',
      storage: 'Sealed and dry to protect essential oils.',
      tags: ['spice', 'star-anise'],
      interests: ['Spice Lover', 'Cooking Lover', 'Premium Gifts'],
      occasions: ['Christmas', 'New Year', 'Thank You'],
      culturalStory: 'Star anise brings dramatic aroma to special-occasion cooking.',
      heritage: 'Favoured in celebratory rice and aromatic stocks.',
      production: 'Pods are dried whole to preserve shape and scent.',
    }),
    p({
      name: 'Saffron',
      slug: 'saffron',
      category: 'Spices',
      price: 4500,
      stock: 40,
      image: img.saffron,
      shortDescription: 'Delicate crimson saffron threads for luxury cooking.',
      description: 'Premium saffron strands for rice, desserts and celebratory feasts.',
      origin: 'Carefully sourced for SpiceBox Lanka',
      ingredients: 'Saffron stigmas (Crocus sativus)',
      usage: 'Steep a few threads in warm water or milk before adding.',
      storage: 'Dark, airtight container; use sparingly.',
      tags: ['spice', 'saffron', 'premium'],
      interests: ['Premium Gifts', 'Spice Lover', 'Cooking Lover'],
      occasions: ['Wedding', 'Anniversary', 'Corporate'],
      culturalStory: 'Saffron is our luxury accent for milestone meals and gifts.',
      heritage: 'Reserved for celebrations and premium hospitality.',
      production: 'Hand-sorted threads packed for freshness.',
      featured: true,
    }),
    p({
      name: 'Paprika',
      slug: 'paprika',
      category: 'Spices',
      price: 680,
      stock: 115,
      image: img.paprika,
      shortDescription: 'Bright paprika with colour and gentle sweetness.',
      description: 'Finely milled paprika for colour, mild sweetness and warmth.',
      origin: 'SpiceBox Lanka blend kitchen',
      ingredients: 'Ground sweet paprika',
      usage: 'Dust over dishes or bloom lightly in oil.',
      storage: 'Away from heat and sunlight.',
      tags: ['spice', 'paprika'],
      interests: ['Spice Lover', 'Cooking Lover'],
      culturalStory: 'Paprika adds colour to modern Sri Lankan-inspired cooking.',
      heritage: 'A colourful bridge between tradition and contemporary kitchens.',
      production: 'Peppers are dried and milled fine.',
    }),
    p({
      name: 'Fennel Seeds',
      slug: 'fennel-seeds',
      category: 'Spices',
      price: 560,
      stock: 120,
      image: img.fennelSeeds,
      shortDescription: 'Sweet fennel seeds with liquorice brightness.',
      description: 'Pale green fennel seeds for curry powders, tea blends and digestives.',
      origin: 'Sri Lanka',
      ingredients: '100% Foeniculum vulgare seeds',
      usage: 'Roast for blends, steep in tea, or use after meals.',
      storage: 'Cool, dry, airtight.',
      tags: ['spice', 'fennel'],
      interests: ['Spice Lover', 'Tea Lover', 'Healthy Lifestyle'],
      culturalStory: 'Fennel is the soft sweet note in many Sri Lankan spice mixes.',
      heritage: 'Used in cooking and traditional after-meal rituals.',
      production: 'Seeds are cleaned and gently dried.',
    }),
    p({
      name: 'Curry Leaves',
      slug: 'curry-leaves',
      category: 'Spices',
      price: 490,
      stock: 150,
      image: img.curryLeaves,
      shortDescription: 'Aromatic curry leaves for authentic tempering.',
      description: 'Dried curry leaves that release citrus-herbal aroma when tempered.',
      origin: 'Home gardens & spice estates, Sri Lanka',
      ingredients: 'Dried Murraya koenigii leaves',
      usage: 'Temper in hot oil with mustard seeds and onion.',
      storage: 'Keep sealed to preserve fragrance.',
      tags: ['spice', 'curry-leaves'],
      interests: ['Spice Lover', 'Traditional Food Lover', 'Cooking Lover'],
      culturalStory: 'Curry leaves are the fragrance that says home across Sri Lanka.',
      heritage: 'Irreplaceable in traditional tempering and curries.',
      production: 'Leaves are shade-dried to lock in aroma.',
    }),
  ])

  const bySlug = Object.fromEntries(products.map((x) => [x.slug, x]))

  await GiftBox.insertMany([
    {
      name: 'Mini SpiceBox',
      slug: 'mini-spicebox',
      description: 'A charming starter — cinnamon, curry powder and cardamom.',
      basePrice: 2500,
      image: img.gift1,
      products: [bySlug['ceylon-cinnamon']._id, bySlug['sri-lankan-curry-powder']._id, bySlug['ceylon-cardamom']._id],
      category: 'Budget',
    },
    {
      name: 'Taste of Sri Lanka',
      slug: 'taste-of-sri-lanka',
      description: 'Cinnamon, pepper, curry powder and cloves — the classic spice journey.',
      basePrice: 5000,
      image: img.gift1,
      products: [
        bySlug['ceylon-cinnamon']._id,
        bySlug['ceylon-black-pepper']._id,
        bySlug['sri-lankan-curry-powder']._id,
        bySlug['ceylon-cloves']._id,
      ],
      category: 'Budget',
    },
    {
      name: 'Premium Ceylon Experience',
      slug: 'premium-ceylon-experience',
      description: 'Cardamom, cinnamon, turmeric, black pepper and curry leaves.',
      basePrice: 7500,
      image: img.gift2,
      products: [
        bySlug['ceylon-cardamom']._id,
        bySlug['ceylon-cinnamon']._id,
        bySlug['turmeric']._id,
        bySlug['ceylon-black-pepper']._id,
        bySlug['curry-leaves']._id,
      ],
      category: 'Premium',
    },
    {
      name: 'Luxury Sri Lankan Heritage Box',
      slug: 'luxury-heritage-box',
      description: 'Our most luxurious spice collection for milestone gifting.',
      basePrice: 10000,
      image: img.gift4,
      products: [
        bySlug['saffron']._id,
        bySlug['ceylon-cinnamon']._id,
        bySlug['ceylon-cardamom']._id,
        bySlug['ceylon-cloves']._id,
        bySlug['star-anise']._id,
        bySlug['nutmeg']._id,
        bySlug['sri-lankan-curry-powder']._id,
        bySlug['red-chili']._id,
      ],
      category: 'Luxury',
    },
  ])

  await Order.create({
    orderId: 'SBL-2026-000001',
    customerSnapshot: { name: 'Nimal Perera', email: 'customer@spiceboxlanka.lk', phone: '0771234567' },
    items: [
      {
        product: bySlug['ceylon-black-pepper']._id,
        name: 'Ceylon Black Pepper',
        image: img.pepper,
        price: 700,
        quantity: 1,
      },
      {
        product: bySlug['ceylon-cinnamon']._id,
        name: 'Ceylon Cinnamon',
        image: img.cinnamon,
        price: 850,
        quantity: 1,
      },
    ],
    delivery: {
      address: '12 Flower Road',
      city: 'Colombo',
      district: 'Colombo',
      postalCode: '00700',
      method: 'Standard Delivery',
      fee: 350,
    },
    payment: { method: 'Demo Card', status: 'Paid', provider: 'Demo' },
    pricing: { subtotal: 1550, packaging: 0, customization: 0, delivery: 350, discount: 0, total: 1900 },
    status: 'Delivered',
  })

  console.log('[seed] Done — admin@spiceboxlanka.lk / admin123 | customer@spiceboxlanka.lk / customer123')
}
